# Generated by Django 3.0.7 on 2020-06-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=2000, unique=True)),
                ('search_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('authour', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
