# Generated by Django 3.0.7 on 2020-06-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=2000, unique=True)),
                ('search_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('authour', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True)),
            ],
        ),
    ]
