# Generated by Django 3.0.7 on 2020-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='authour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
