# Generated by Django 3.0.7 on 2020-06-23 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20200618_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='authour',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='rating',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='content',
            name='search_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('score', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
