# Generated by Django 3.0.8 on 2020-07-06 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20200701_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media_type',
            field=models.CharField(choices=[('RD', 'Radio'), ('GP', 'Graphic'), ('FR', 'Forum'), ('GM', ' Game'), ('SM', 'Social_Media'), ('VD', 'Video'), ('BG', 'Blog'), ('DA', 'Digial_Article'), ('BK', 'Book'), ('PF', 'PDF'), ('AS', 'Academic_Study'), ('OT', 'Other')], default='DA', max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
