# Generated by Django 3.0.8 on 2020-07-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_content_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
