# Generated by Django 3.0.8 on 2020-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200718_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
