# Generated by Django 3.0.8 on 2020-07-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200719_2014'),
        ('core', '0014_auto_20200719_2013'),
    ]

    operations = [
    ]
