# Generated by Django 3.0.7 on 2020-07-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200621_0207'),
        ('core', '0005_auto_20200623_0400'),
    ]

    operations = [
    ]
