# Generated by Django 3.0.8 on 2020-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200717_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
