# Generated by Django 3.0.8 on 2020-07-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20200721_2135'),
        ('core', '0015_merge_20200721_1811'),
    ]

    operations = [
    ]
