# Generated by Django 3.0.8 on 2020-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20200721_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_moderation_score',
            field=models.IntegerField(choices=[(0, 'Safe'), (1, 'Warning'), (2, 'No Show')], default=0),
        ),
    ]
