# Generated by Django 3.0.8 on 2020-07-29 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_content_image_moderation_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedContentList',
        ),
    ]
