# Generated by Django 3.0.8 on 2020-09-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_savedcontentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='upvote_count',
        ),
    ]
