# Generated by Django 3.0.8 on 2020-08-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_savedcontentlist'),
        ('users', '0004_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvote_users', to='core.Rating'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvote_users', to='core.Rating'),
        ),
    ]
